# Generated by Django 3.0.4 on 2020-04-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='last_modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
