# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-06 19:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0043_project_raps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nrmrlqapprequirement',
            name='is_active',
            field=models.CharField(blank=True, choices=[('', ''), ('Y', 'Yes'), ('N', 'No')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='is_active',
            field=models.CharField(blank=True, choices=[('', ''), ('Y', 'Yes'), ('N', 'No')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='project_collaborators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='collaborators_old',
            field=models.ManyToManyField(blank=True, related_name='collaborators', to='persons.Person'),
        ),
        migrations.AlterField(
            model_name='project',
            name='participating_organizations',
            field=models.ManyToManyField(blank=True, to='projects.ParticipatingOrganization'),
        ),
        migrations.AlterField(
            model_name='project',
            name='public_or_private',
            field=models.CharField(blank=True, choices=[('', ''), ('PUBLIC', 'PUBLIC'), ('PRIVATE', 'PRIVATE')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='qmp_required',
            field=models.CharField(blank=True, choices=[('', ''), ('Y', 'Yes'), ('N', 'No')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='suspend_reminder',
            field=models.CharField(choices=[('', ''), ('Y', 'Yes'), ('N', 'No')], default='N', max_length=2),
        ),
        migrations.AlterField(
            model_name='projectattachment',
            name='is_qapp_review_file',
            field=models.CharField(choices=[('', ''), ('Y', 'Yes'), ('N', 'No')], default='N', max_length=2),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='is_active',
            field=models.CharField(blank=True, choices=[('', ''), ('Y', 'Yes'), ('N', 'No')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='projectlog',
            name='are_corrective_actions_completed',
            field=models.CharField(blank=True, choices=[('', ''), ('Y', 'Y'), ('N', 'N'), ('NA', 'NA')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='projectlog',
            name='is_finding_resolved',
            field=models.CharField(blank=True, choices=[('', ''), ('Y', 'Yes'), ('N', 'No')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='projectlog',
            name='public_or_private',
            field=models.CharField(blank=True, choices=[('', ''), ('PUBLIC', 'PUBLIC'), ('PRIVATE', 'PRIVATE')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='projectlog',
            name='qa_review_required',
            field=models.CharField(blank=True, choices=[('', ''), ('Y', 'Yes'), ('N', 'No')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='projectlog',
            name='software_status',
            field=models.CharField(blank=True, choices=[('', ''), ('Active', 'Active'), ('Inactive', 'Inactive')], max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='projectlogtype',
            name='is_active',
            field=models.CharField(blank=True, choices=[('', ''), ('Y', 'Yes'), ('N', 'No')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='projectrequest',
            name='dqi_met',
            field=models.CharField(blank=True, choices=[('', ''), ('Y', 'Yes'), ('N', 'No')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='projectrequest',
            name='dqi_met_some',
            field=models.CharField(blank=True, choices=[('', ''), ('Y', 'Yes'), ('N', 'No')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='projectrequest',
            name='dqi_met_some_bad_data',
            field=models.CharField(blank=True, choices=[('', ''), ('Y', 'Yes'), ('N', 'No')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='projectrequest',
            name='dqi_na',
            field=models.CharField(blank=True, choices=[('', ''), ('Y', 'Yes'), ('N', 'No')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='projectrequest',
            name='was_qapp_prepared',
            field=models.CharField(blank=True, choices=[('', ''), ('Y', 'Yes'), ('N', 'No')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='projectrequest',
            name='was_qapp_required',
            field=models.CharField(blank=True, choices=[('', ''), ('Y', 'Yes'), ('N', 'No')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='projectstatus',
            name='is_active',
            field=models.CharField(blank=True, choices=[('', ''), ('Y', 'Yes'), ('N', 'No')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='projecttype',
            name='is_active',
            field=models.CharField(blank=True, choices=[('', ''), ('Y', 'Yes'), ('N', 'No')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='qacategory',
            name='is_active',
            field=models.CharField(blank=True, choices=[('', ''), ('Y', 'Yes'), ('N', 'No')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='qappstatus',
            name='is_active',
            field=models.CharField(blank=True, choices=[('', ''), ('Y', 'Yes'), ('N', 'No')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='is_active',
            field=models.CharField(blank=True, choices=[('', ''), ('Y', 'Yes'), ('N', 'No')], max_length=2, null=True),
        ),
    ]
