# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-11 19:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0045_new_project_raps'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='hsr_rap_extensions',
            new_name='hsrp_rap_extensions',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='hsr_rap_numbers',
            new_name='hsrp_rap_numbers',
        ),
    ]
