# Generated by Django 2.0.5 on 2018-08-20 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0046_auto_20180411_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectattachment',
            name='is_latest_qapp_doc',
            field=models.CharField(choices=[('', ''), ('Y', 'Yes'), ('N', 'No')], default='N', max_length=2),
        ),
        migrations.AddField(
            model_name='projectattachment',
            name='is_latest_qapp_pdf',
            field=models.CharField(choices=[('', ''), ('Y', 'Yes'), ('N', 'No')], default='N', max_length=2),
        ),
    ]
