# Generated by Django 2.0.7 on 2018-09-04 05:18
# Then edited by Jane Lin before deployment to change the name of the field
# and make it a BooleanField.
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0047_auto_20180820_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='post_qapp_on_ordatwork',
            field=models.BooleanField(default=True),
        ),
    ]
