# Generated by Django 2.1.3 on 2018-12-13 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0049_project_orgs'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='restrict_ext_package_files',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='restrict_qapp_files',
            field=models.BooleanField(default=False),
        ),
        migrations.RunSQL("update projects_project set restrict_qapp_files = NOT post_qapp_on_ordatwork;", reverse_sql=""),
    ]
