# Generated by Django 2.1.3 on 2018-12-13 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0050_change_qapp_restriction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='post_qapp_on_ordatwork'
        ),

    ]
