# Generated by Django 2.1.7 on 2019-02-22 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0051_remove_ordatwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='qappreview',
            name='cc_email_list',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
