# Generated by Django 2.2.1 on 2019-06-18 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0052_qappreview_cc_email_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='alt_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='previous_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectlog',
            name='alt_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectlog',
            name='previous_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
