# Generated by Django 2.2.2 on 2019-07-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0053_auto_20190617_1948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectstatus',
            options={'ordering': ['sort_number']},
        ),
        migrations.AddField(
            model_name='projectstatus',
            name='sort_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
