# Generated by Django 2.2.3 on 2019-07-15 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0054_auto_20190702_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='qa_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_qa_manager', to=settings.AUTH_USER_MODEL),
        ),
    ]
