# Generated by Django 2.2.3 on 2019-07-18 21:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0055_project_qa_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='previous_qams',
            field=models.ManyToManyField(blank=True, related_name='previous_qams', to=settings.AUTH_USER_MODEL),
        ),
    ]
