# Generated by Django 2.2.3 on 2019-08-20 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0059_auto_20190820_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlog_update_history',
            name='review_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.ReviewType'),
        ),
    ]
