# Generated by Django 3.0.4 on 2020-03-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0064_projectlog_qapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='suspend_reminder',
            field=models.CharField(choices=[('', ''), ('Y', 'Yes'), ('N', 'No')], default='N', max_length=4),
        ),
        migrations.AlterField(
            model_name='projectattachment',
            name='is_latest_qapp_doc',
            field=models.CharField(choices=[('', ''), ('Y', 'Yes'), ('N', 'No')], default='N', max_length=4),
        ),
        migrations.AlterField(
            model_name='projectattachment',
            name='is_latest_qapp_pdf',
            field=models.CharField(choices=[('', ''), ('Y', 'Yes'), ('N', 'No')], default='N', max_length=4),
        ),
        migrations.AlterField(
            model_name='projectattachment',
            name='is_qapp_review_file',
            field=models.CharField(choices=[('', ''), ('Y', 'Yes'), ('N', 'No')], default='N', max_length=4),
        ),
    ]
