# Generated by Django 2.2.6 on 2019-10-18 16:07

from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingTool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('search', models.CharField(max_length=255)),
                ('article_title', models.CharField(max_length=255)),
                ('date_accessed', models.DateTimeField(default=django.utils.timezone.now)),
                ('comments', models.CharField(max_length=255)),
            ],
        ),
    ]
