# Generated by Django 2.2.6 on 2019-10-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodWaste', '0002_auto_20191018_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingtool',
            name='phone',
            field=models.CharField(max_length=32),
        ),
    ]
