# Generated by Django 2.2.6 on 2019-10-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodWaste', '0003_auto_20191022_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingtool',
            name='citation',
            field=models.CharField(default=' ', max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trackingtool',
            name='comments',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
