# Generated by Django 2.2.6 on 2019-10-23 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('FoodWaste', '0004_auto_20191022_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondaryDataSharingTeamMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('can_edit', models.BooleanField()),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_data_teams', to='FoodWaste.TrackingTool')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_secondary_data', to='teams.Team')),
            ],
        ),
        migrations.AddField(
            model_name='trackingtool',
            name='teams',
            field=models.ManyToManyField(through='FoodWaste.SecondaryDataSharingTeamMap', to='teams.Team'),
        ),
    ]
