# Generated by Django 2.2.6 on 2019-11-01 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataSearch', '0004_auto_20191101_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='existingdata',
            name='source',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='existing_data_sources', to='DataSearch.ExistingDataSource'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='existingdata',
            name='source_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
