# Generated by Django 2.2.6 on 2019-11-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataSearch', '0005_auto_20191101_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='existingdata',
            name='keywords',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='existingdata',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
