# Generated by Django 3.0.2 on 2020-01-31 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataSearch', '0010_division_fixture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qualityassuranceprojectplan',
            old_name='epa_project_lead_1',
            new_name='division_branch',
        ),
        migrations.RenameField(
            model_name='qualityassuranceprojectplan',
            old_name='epa_project_lead_2',
            new_name='prepared_by',
        ),
        migrations.RenameField(
            model_name='qualityassuranceprojectplan',
            old_name='input_1',
            new_name='strap',
        ),
        migrations.RenameField(
            model_name='qualityassuranceprojectplan',
            old_name='input_2',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='qualityassuranceprojectplan',
            name='input_3',
        ),
        migrations.RemoveField(
            model_name='qualityassuranceprojectplan',
            name='input_4',
        ),
        migrations.RemoveField(
            model_name='qualityassuranceprojectplan',
            name='input_5',
        ),
        migrations.RemoveField(
            model_name='qualityassuranceprojectplan',
            name='input_6',
        ),
        migrations.RemoveField(
            model_name='qualityassuranceprojectplan',
            name='prepared_by_1',
        ),
        migrations.RemoveField(
            model_name='qualityassuranceprojectplan',
            name='prepared_by_2',
        ),
        migrations.CreateModel(
            name='QualityAssuranceProjectLead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='DataSearch.QualityAssuranceProjectPlan')),
            ],
        ),
    ]
