# Generated by Django 3.0.4 on 2020-04-23 13:21

import constants.utils
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('DataSearch', '0002_datasource_fixture'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='existingdatasharingteammap',
            unique_together={('data', 'team')},
        ),
    ]
