# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-06 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sop_tab', '0028_remove_soptab_all_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='is_active',
            field=models.CharField(blank=True, choices=[('', ''), ('Y', 'Yes'), ('N', 'No')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='soptab',
            name='is_current',
            field=models.CharField(choices=[('', ''), ('Y', 'Yes'), ('N', 'No')], default='Y', max_length=2),
        ),
        migrations.AlterField(
            model_name='soptab',
            name='participating_orgs',
            field=models.ManyToManyField(blank=True, to='projects.ParticipatingOrganization'),
        ),
        migrations.AlterField(
            model_name='soptab',
            name='programs',
            field=models.ManyToManyField(blank=True, to='projects.Program'),
        ),
        migrations.AlterField(
            model_name='soptab',
            name='projects',
            field=models.ManyToManyField(blank=True, to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='soptab',
            name='related_sops',
            field=models.ManyToManyField(blank=True, related_name='_soptab_related_sops_+', to='sop_tab.SOPTab'),
        ),
        migrations.AlterField(
            model_name='soptab',
            name='suspend_reminder',
            field=models.CharField(choices=[('', ''), ('Y', 'Yes'), ('N', 'No')], default='N', max_length=2),
        ),
        migrations.AlterField(
            model_name='soptab_muraltype',
            name='is_active',
            field=models.CharField(blank=True, choices=[('', ''), ('Y', 'Yes'), ('N', 'No')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='soptab_status',
            name='is_active',
            field=models.CharField(blank=True, choices=[('', ''), ('Y', 'Yes'), ('N', 'No')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='soptab_type',
            name='is_active',
            field=models.CharField(blank=True, choices=[('', ''), ('Y', 'Yes'), ('N', 'No')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='soptabattachment',
            name='include_in_email',
            field=models.CharField(choices=[('', ''), ('Y', 'Yes'), ('N', 'No')], default='N', max_length=2),
        ),
        migrations.AlterField(
            model_name='soptabattachment',
            name='is_latest_sop',
            field=models.CharField(choices=[('', ''), ('Y', 'Yes'), ('N', 'No')], default='N', max_length=2),
        ),
        migrations.AlterField(
            model_name='soptabattachment',
            name='is_review_file',
            field=models.CharField(choices=[('', ''), ('Y', 'Yes'), ('N', 'No')], default='N', max_length=2),
        ),
        migrations.AlterField(
            model_name='subdiscipline',
            name='is_active',
            field=models.CharField(blank=True, choices=[('', ''), ('Y', 'Yes'), ('N', 'No')], max_length=4, null=True),
        ),
    ]
