# Generated by Django 2.1.7 on 2019-02-22 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sop_tab', '0029_auto_20180406_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='sopreminder',
            name='cc_email_list',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
