# Generated by Django 2.2.6 on 2019-10-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataSearch', '0006_trackingtool_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingtool',
            name='disclaimer_req',
            field=models.BooleanField(default=True),
        ),
    ]
