# Generated by Django 2.2.6 on 2019-10-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataSearch', '0007_trackingtool_disclaimer_req'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingtool',
            name='disclaimer_req',
            field=models.BooleanField(),
        ),
    ]
