# Generated by Django 2.2.6 on 2019-10-24 12:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DataSearch', '0009_auto_20191024_0542'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrackingTool',
            new_name='SecondaryExistingData',
        ),
    ]
