# Generated by Django 3.0.3 on 2020-02-07 20:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Qapp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division_branch', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('qa_category', models.CharField(max_length=255)),
                ('intra_extra', models.CharField(max_length=64)),
                ('revision_number', models.CharField(max_length=255)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('prepared_by', models.CharField(max_length=255)),
                ('strap', models.CharField(max_length=255)),
                ('tracking_id', models.CharField(max_length=255)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='qar5.Division')),
            ],
        ),
        migrations.CreateModel(
            name='QappApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_plan_title', models.CharField(max_length=255)),
                ('activity_number', models.CharField(max_length=255)),
                ('qapp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qar5.Qapp')),
            ],
        ),
        migrations.CreateModel(
            name='QappLead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('qapp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qar5.Qapp')),
            ],
        ),
        migrations.CreateModel(
            name='QappApprovalSignature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intramural', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('signature', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('qapp_approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qar5.QappApproval')),
            ],
        ),
    ]
