# Generated by Django 3.0.3 on 2020-02-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qar5', '0002_division_fixture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qappapprovalsignature',
            name='intramural',
        ),
        migrations.AddField(
            model_name='qappapprovalsignature',
            name='intra_extra',
            field=models.CharField(default='Intramural', max_length=32),
            preserve_default=False,
        ),
    ]
