# Generated by Django 3.0.3 on 2020-02-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qar5', '0003_auto_20200210_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qappapprovalsignature',
            name='intra_extra',
        ),
        migrations.AddField(
            model_name='qappapprovalsignature',
            name='contractor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='qappapprovalsignature',
            name='date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='qappapprovalsignature',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='qappapprovalsignature',
            name='signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
