# Generated by Django 3.0.3 on 2020-02-12 15:29

import constants.utils
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('qar5', '0004_auto_20200210_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qappapprovalsignature',
            name='contractor',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.CreateModel(
            name='SectionD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d1', models.CharField(max_length=2047)),
                ('d2', models.CharField(max_length=2047)),
                ('d3', models.CharField(max_length=2047)),
                ('qapp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qar5.Qapp')),
            ],
        ),
        migrations.CreateModel(
            name='SectionC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qapp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qar5.Qapp')),
            ],
        ),
        migrations.CreateModel(
            name='SectionB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b1_2', models.CharField(max_length=2047)),
                ('b1_3', models.CharField(max_length=2047)),
                ('b1_4', models.CharField(max_length=2047)),
                ('b1_5', models.CharField(max_length=2047)),
                ('b2_1', models.CharField(max_length=2047)),
                ('b2_2', models.CharField(max_length=2047)),
                ('b2_3', models.CharField(max_length=2047)),
                ('b2_4', models.CharField(max_length=2047)),
                ('b2_5', models.CharField(max_length=2047)),
                ('b3', models.CharField(max_length=2047)),
                ('b4', models.CharField(max_length=2047)),
                ('qapp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qar5.Qapp')),
            ],
        ),
        migrations.CreateModel(
            name='SectionA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a3', models.CharField(max_length=2047)),
                ('a4', models.CharField(max_length=2047)),
                ('a4_chart', models.FileField(blank=True, null=True, upload_to=constants.utils.get_attachment_storage_path)),
                ('a5', models.CharField(max_length=2047)),
                ('a6', models.CharField(max_length=2047)),
                ('a7', models.CharField(max_length=2047)),
                ('a8', models.CharField(max_length=2047)),
                ('a9', models.CharField(max_length=2047)),
                ('a9_drive_path', models.CharField(max_length=255)),
                ('qapp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qar5.Qapp')),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('effective_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('initial_version', models.CharField(max_length=255)),
                ('qapp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qar5.Qapp')),
            ],
        ),
    ]
