# Generated by Django 3.0.3 on 2020-02-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qar5', '0005_auto_20200212_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionc',
            name='c1',
            field=models.CharField(default='', max_length=2047),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sectionc',
            name='c2',
            field=models.CharField(default='', max_length=2047),
            preserve_default=False,
        ),
    ]
