# Generated by Django 3.0.3 on 2020-02-12 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qar5', '0006_auto_20200212_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revision',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sectiona',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sectionb',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sectionc',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sectiond',
            name='id',
        ),
        migrations.AlterField(
            model_name='revision',
            name='qapp',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='qar5.Qapp'),
        ),
        migrations.AlterField(
            model_name='sectiona',
            name='qapp',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='qar5.Qapp'),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='qapp',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='qar5.Qapp'),
        ),
        migrations.AlterField(
            model_name='sectionc',
            name='qapp',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='qar5.Qapp'),
        ),
        migrations.AlterField(
            model_name='sectiond',
            name='qapp',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='qar5.Qapp'),
        ),
    ]
