# Generated by Django 3.0.3 on 2020-03-16 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qar5', '0007_auto_20200316_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionc',
            name='c1',
        ),
        migrations.RemoveField(
            model_name='sectionc',
            name='c2',
        ),
    ]
