# Generated by Django 3.0.3 on 2020-03-16 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qar5', '0008_auto_20200316_1455'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SectionC',
        ),
    ]
