# Generated by Django 3.0.3 on 2020-03-19 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qar5', '0009_delete_sectionc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qappapproval',
            name='qapp',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='qar5.Qapp'),
        ),
        migrations.AlterField(
            model_name='qappsharingteammap',
            name='can_edit',
            field=models.BooleanField(default=True),
        ),
    ]
