# Generated by Django 3.0.4 on 2020-03-20 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qar5', '0010_auto_20200319_0834'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionC',
            fields=[
                ('qapp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='qar5.Qapp')),
                ('c3', models.CharField(max_length=2047)),
            ],
        ),
    ]
