# Generated by Django 3.0.4 on 2020-03-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qar5', '0012_auto_20200324_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionb',
            name='b1_1',
            field=models.CharField(blank=True, max_length=2047, null=True),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='b1_2',
            field=models.CharField(blank=True, max_length=2047, null=True),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='b1_3',
            field=models.CharField(blank=True, max_length=2047, null=True),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='b1_4',
            field=models.CharField(blank=True, max_length=2047, null=True),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='b1_5',
            field=models.CharField(blank=True, max_length=2047, null=True),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='b1_6',
            field=models.CharField(blank=True, max_length=2047, null=True),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='b1_7',
            field=models.CharField(blank=True, max_length=2047, null=True),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='b1_8',
            field=models.CharField(blank=True, max_length=2047, null=True),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='b1_9',
            field=models.CharField(blank=True, max_length=2047, null=True),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='b2_1',
            field=models.CharField(blank=True, max_length=2047, null=True),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='b2_2',
            field=models.CharField(blank=True, max_length=2047, null=True),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='b2_3',
            field=models.CharField(blank=True, max_length=2047, null=True),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='b2_4',
            field=models.CharField(blank=True, max_length=2047, null=True),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='b2_5',
            field=models.CharField(blank=True, max_length=2047, null=True),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='b2_6',
            field=models.CharField(blank=True, max_length=2047, null=True),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='b2_7',
            field=models.CharField(blank=True, max_length=2047, null=True),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='b2_8',
            field=models.CharField(blank=True, max_length=2047, null=True),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='b3_1',
            field=models.CharField(blank=True, max_length=2047, null=True),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='b3_10',
            field=models.CharField(blank=True, max_length=2047, null=True),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='b3_2',
            field=models.CharField(blank=True, max_length=2047, null=True),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='b3_3',
            field=models.CharField(blank=True, max_length=2047, null=True),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='b3_4',
            field=models.CharField(blank=True, max_length=2047, null=True),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='b3_5',
            field=models.CharField(blank=True, max_length=2047, null=True),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='b3_6',
            field=models.CharField(blank=True, max_length=2047, null=True),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='b3_7',
            field=models.CharField(blank=True, max_length=2047, null=True),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='b3_8',
            field=models.CharField(blank=True, max_length=2047, null=True),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='b3_9',
            field=models.CharField(blank=True, max_length=2047, null=True),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='b4_1',
            field=models.CharField(blank=True, max_length=2047, null=True),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='b4_2',
            field=models.CharField(blank=True, max_length=2047, null=True),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='b4_3',
            field=models.CharField(blank=True, max_length=2047, null=True),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='b4_4',
            field=models.CharField(blank=True, max_length=2047, null=True),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='b4_5',
            field=models.CharField(blank=True, max_length=2047, null=True),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='b5_1',
            field=models.CharField(blank=True, max_length=2047, null=True),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='b5_2',
            field=models.CharField(blank=True, max_length=2047, null=True),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='b6_1',
            field=models.CharField(blank=True, max_length=2047, null=True),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='b6_2',
            field=models.CharField(blank=True, max_length=2047, null=True),
        ),
    ]
