# Generated by Django 3.0.4 on 2020-03-25 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qar5', '0013_auto_20200325_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionb',
            name='b1_6',
        ),
        migrations.RemoveField(
            model_name='sectionb',
            name='b1_7',
        ),
        migrations.RemoveField(
            model_name='sectionb',
            name='b1_8',
        ),
        migrations.RemoveField(
            model_name='sectionb',
            name='b1_9',
        ),
    ]
