# Generated by Django 3.0.3 on 2020-03-27 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qar5', '0014_auto_20200325_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionc',
            name='c3',
        ),
    ]
