# Generated by Django 3.0.4 on 2020-04-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qar5', '0015_remove_sectionc_c3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='qapp',
            name='division_branch',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='qapp',
            name='qa_category',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='qapp',
            name='revision_number',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='qapp',
            name='strap',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='qapp',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='qapp',
            name='tracking_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='qappapproval',
            name='activity_number',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='qappapproval',
            name='project_plan_title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='qappapprovalsignature',
            name='date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qappapprovalsignature',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qappapprovalsignature',
            name='signature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qapplead',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='revision',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='revision',
            name='initial_version',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='revision',
            name='revision',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sectiona',
            name='a3',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sectiona',
            name='a4',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sectiona',
            name='a5',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sectiona',
            name='a6',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sectiona',
            name='a7',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sectiona',
            name='a8',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sectiona',
            name='a9',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sectiona',
            name='a9_drive_path',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='b1_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='b1_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='b1_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='b1_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='b1_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='b2_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='b2_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='b2_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='b2_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='b2_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='b2_6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='b2_7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='b2_8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='b3_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='b3_10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='b3_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='b3_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='b3_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='b3_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='b3_6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='b3_7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='b3_8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='b3_9',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='b4_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='b4_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='b4_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='b4_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='b4_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='b5_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='b5_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='b6_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sectionb',
            name='b6_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sectionbtype',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sectiond',
            name='d1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sectiond',
            name='d2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sectiond',
            name='d3',
            field=models.TextField(),
        ),
    ]
