# Generated by Django 3.0.4 on 2020-04-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qar5', '0016_auto_20200406_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectiona',
            name='a2',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
