# Generated by Django 2.1.7 on 2019-02-18 23:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0008_lab_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='qams',
            field=models.ManyToManyField(blank=True, related_name='branch_qams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='division',
            name='qams',
            field=models.ManyToManyField(blank=True, related_name='division_qams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lab',
            name='qams',
            field=models.ManyToManyField(blank=True, related_name='lab_qams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='office',
            name='qams',
            field=models.ManyToManyField(blank=True, related_name='office_qams', to=settings.AUTH_USER_MODEL),
        ),
    ]
