# Generated by Django 2.2.6 on 2019-10-24 12:48

import FoodWaste.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to=FoodWaste.models.get_attachment_storage_path)),
            ],
        ),
        migrations.CreateModel(
            name='DataAttachmentMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment_secondary_data', to='FoodWaste.Attachment')),
            ],
        ),
        migrations.CreateModel(
            name='SecondaryDataSharingTeamMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('can_edit', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SecondaryExistingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=32)),
                ('search', models.CharField(max_length=255)),
                ('article_title', models.CharField(max_length=255)),
                ('disclaimer_req', models.BooleanField()),
                ('citation', models.CharField(max_length=512)),
                ('date_accessed', models.DateTimeField(default=django.utils.timezone.now)),
                ('comments', models.CharField(blank=True, max_length=512, null=True)),
                ('attachments', models.ManyToManyField(through='FoodWaste.DataAttachmentMap', to='FoodWaste.Attachment')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('teams', models.ManyToManyField(through='FoodWaste.SecondaryDataSharingTeamMap', to='teams.Team')),
            ],
        ),
        migrations.AddField(
            model_name='secondarydatasharingteammap',
            name='data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_data_teams', to='FoodWaste.SecondaryExistingData'),
        ),
        migrations.AddField(
            model_name='secondarydatasharingteammap',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_secondary_data', to='teams.Team'),
        ),
        migrations.AddField(
            model_name='dataattachmentmap',
            name='data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_data_attachments', to='FoodWaste.SecondaryExistingData'),
        ),
    ]
