# Generated by Django 2.2.6 on 2019-10-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodWaste', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingtool',
            name='comments',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
