# Generated by Django 2.2.6 on 2019-10-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodWaste', '0002_attachment_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondaryexistingdata',
            name='comments',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
