# Generated by Django 2.2.6 on 2019-10-25 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0001_initial'),
        ('FoodWaste', '0003_auto_20191025_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExistingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=32)),
                ('search', models.CharField(max_length=255)),
                ('article_title', models.CharField(max_length=255)),
                ('disclaimer_req', models.BooleanField()),
                ('citation', models.CharField(max_length=512)),
                ('date_accessed', models.DateTimeField(default=django.utils.timezone.now)),
                ('comments', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExistingDataSharingTeamMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('can_edit', models.BooleanField()),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='existing_data_teams', to='FoodWaste.ExistingData')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_existing_data', to='teams.Team')),
            ],
        ),
        migrations.RemoveField(
            model_name='secondaryexistingdata',
            name='attachments',
        ),
        migrations.RemoveField(
            model_name='secondaryexistingdata',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='secondaryexistingdata',
            name='teams',
        ),
        migrations.AlterField(
            model_name='dataattachmentmap',
            name='attachment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment_existing_data', to='FoodWaste.Attachment'),
        ),
        migrations.AlterField(
            model_name='dataattachmentmap',
            name='data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='existing_data_attachments', to='FoodWaste.ExistingData'),
        ),
        migrations.DeleteModel(
            name='SecondaryDataSharingTeamMap',
        ),
        migrations.DeleteModel(
            name='SecondaryExistingData',
        ),
        migrations.AddField(
            model_name='existingdata',
            name='attachments',
            field=models.ManyToManyField(through='FoodWaste.DataAttachmentMap', to='FoodWaste.Attachment'),
        ),
        migrations.AddField(
            model_name='existingdata',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='existingdata',
            name='teams',
            field=models.ManyToManyField(through='FoodWaste.ExistingDataSharingTeamMap', to='teams.Team'),
        ),
    ]
