# Generated by Django 2.2.7 on 2020-01-30 19:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FoodWaste', '0007_datasource_fixture'),
    ]

    operations = [
        migrations.CreateModel(
            name='QappApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_plan_title', models.CharField(max_length=255)),
                ('activity_number', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='QualityAssuranceProjectPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(max_length=255)),
                ('input_1', models.CharField(max_length=255)),
                ('input_2', models.CharField(max_length=255)),
                ('epa_project_lead_1', models.CharField(max_length=255)),
                ('epa_project_lead_2', models.CharField(max_length=255)),
                ('qa_category', models.CharField(max_length=255)),
                ('intra_extra', models.CharField(max_length=64)),
                ('revision_number', models.CharField(max_length=255)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('prepared_by_1', models.CharField(max_length=255)),
                ('prepared_by_2', models.CharField(max_length=255)),
                ('input_3', models.CharField(max_length=255)),
                ('input_4', models.CharField(max_length=255)),
                ('input_5', models.CharField(max_length=255)),
                ('input_6', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='QappApprovalSignature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intramural', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('signature', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('qapp_approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodWaste.QappApproval')),
            ],
        ),
        migrations.AddField(
            model_name='qappapproval',
            name='qapp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodWaste.QualityAssuranceProjectPlan'),
        ),
    ]
