# Generated by Django 3.0.2 on 2020-01-31 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodWaste', '0011_auto_20200131_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualityassuranceprojectplan',
            name='tracking_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
