# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
from django.conf import settings
import persons.models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('labs', '0001_initial'),
        ('divisions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressType',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_on', models.DateField(auto_now_add=True, null=True)),
                ('modified_on', models.DateField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.CharField(max_length=255, null=True, blank=True)),
                ('last_modified_by', models.CharField(max_length=255, null=True, blank=True)),
                ('share', models.CharField(blank=True, max_length=5, null=True, choices=[(b'', b''), (b'Y', b'Y'), (b'N', b'N')])),
                ('attachment', models.FileField(null=True, upload_to=persons.models.get_person_storage_path, blank=True)),
                ('the_name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=models.CASCADE, blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailType',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_on', models.DateField(auto_now_add=True, null=True)),
                ('modified_on', models.DateField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.CharField(max_length=255, null=True, blank=True)),
                ('last_modified_by', models.CharField(max_length=255, null=True, blank=True)),
                ('share', models.CharField(blank=True, max_length=5, null=True, choices=[(b'', b''), (b'Y', b'Y'), (b'N', b'N')])),
                ('attachment', models.FileField(null=True, upload_to=persons.models.get_person_storage_path, blank=True)),
                ('the_name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=models.CASCADE, blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_on', models.DateField(auto_now_add=True, null=True)),
                ('modified_on', models.DateField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.CharField(max_length=255, null=True, blank=True)),
                ('last_modified_by', models.CharField(max_length=255, null=True, blank=True)),
                ('is_reviewer', models.CharField(blank=True, max_length=5, null=True, choices=[(b'', b''), (b'Y', b'Y'), (b'N', b'N')])),
                ('attachment', models.FileField(null=True, upload_to=persons.models.get_person_storage_path, blank=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('badge_number', models.CharField(max_length=25, null=True, blank=True)),
                ('other_number', models.CharField(max_length=25, null=True, blank=True)),
                ('weblink', models.CharField(max_length=255, null=True, blank=True)),
                ('ordering', models.DecimalField(null=True, max_digits=10, decimal_places=1, blank=True)),
                ('title', models.CharField(max_length=255, null=True, blank=True)),
                ('salutation', models.CharField(max_length=255, null=True, blank=True)),
                ('date_started', models.DateField(null=True, blank=True)),
                ('date_ended', models.DateField(null=True, blank=True)),
                ('branch', models.ForeignKey(on_delete=models.CASCADE, blank=True, to='branches.Branch', null=True)),
                ('division', models.ForeignKey(on_delete=models.CASCADE, blank=True, to='divisions.Division', null=True)),
                ('lab', models.ForeignKey(on_delete=models.CASCADE, blank=True, to='labs.Lab', null=True)),
            ],
            options={
                'ordering': ['ordering', 'last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='PersonAddress',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_on', models.DateField(auto_now_add=True, null=True)),
                ('modified_on', models.DateField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.CharField(max_length=255, null=True, blank=True)),
                ('last_modified_by', models.CharField(max_length=255, null=True, blank=True)),
                ('share', models.CharField(blank=True, max_length=5, null=True, choices=[(b'', b''), (b'Y', b'Y'), (b'N', b'N')])),
                ('attachment', models.FileField(null=True, upload_to=persons.models.get_person_storage_path, blank=True)),
                ('street_address_01', models.CharField(max_length=255, null=True, blank=True)),
                ('street_address_02', models.CharField(max_length=255, null=True, blank=True)),
                ('city', models.CharField(max_length=255, null=True, blank=True)),
                ('state', models.CharField(max_length=255, null=True, blank=True)),
                ('zipcode', models.CharField(max_length=255, null=True, blank=True)),
                ('mail_station', models.CharField(max_length=255, null=True, blank=True)),
                ('building', models.CharField(max_length=255, null=True, blank=True)),
                ('private_mailbox_designator', models.CharField(max_length=255, null=True, blank=True)),
                ('special_instruction', models.CharField(max_length=255, null=True, blank=True)),
                ('region', models.CharField(max_length=255, null=True, blank=True)),
                ('title', models.CharField(max_length=255, null=True, blank=True)),
                ('serving', models.CharField(max_length=255, null=True, blank=True)),
                ('office', models.CharField(max_length=255, null=True, blank=True)),
                ('address_type', models.ForeignKey(on_delete=models.CASCADE, blank=True, to='persons.AddressType', null=True)),
                ('person', models.ForeignKey(on_delete=models.CASCADE, blank=True, to='persons.Person', null=True)),
                ('user', models.ForeignKey(on_delete=models.CASCADE, blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonAttachment',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_on', models.DateField(auto_now_add=True, null=True)),
                ('modified_on', models.DateField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.CharField(max_length=255, null=True, blank=True)),
                ('last_modified_by', models.CharField(max_length=255, null=True, blank=True)),
                ('share', models.CharField(blank=True, max_length=5, null=True, choices=[(b'', b''), (b'Y', b'Y'), (b'N', b'N')])),
                ('attachment', models.FileField(null=True, upload_to=persons.models.get_person_storage_path, blank=True)),
                ('person', models.ForeignKey(on_delete=models.CASCADE, blank=True, to='persons.Person', null=True)),
                ('user', models.ForeignKey(on_delete=models.CASCADE, blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonDivisionBranch',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_on', models.DateField(auto_now_add=True, null=True)),
                ('modified_on', models.DateField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.CharField(max_length=255, null=True, blank=True)),
                ('last_modified_by', models.CharField(max_length=255, null=True, blank=True)),
                ('share', models.CharField(blank=True, max_length=5, null=True, choices=[(b'', b''), (b'Y', b'Y'), (b'N', b'N')])),
                ('attachment', models.FileField(null=True, upload_to=persons.models.get_person_storage_path, blank=True)),
                ('badge_number', models.CharField(max_length=25, null=True, blank=True)),
                ('other_number', models.CharField(max_length=25, null=True, blank=True)),
                ('weblink', models.CharField(max_length=255, null=True, blank=True)),
                ('ordering', models.DecimalField(null=True, max_digits=10, decimal_places=1, blank=True)),
                ('title', models.CharField(max_length=255, null=True, blank=True)),
                ('salutation', models.CharField(max_length=255, null=True, blank=True)),
                ('date_started', models.DateField(null=True, blank=True)),
                ('date_ended', models.DateField(null=True, blank=True)),
                ('branch', models.ForeignKey(on_delete=models.CASCADE, blank=True, to='branches.Branch', null=True)),
                ('division', models.ForeignKey(on_delete=models.CASCADE, blank=True, to='divisions.Division', null=True)),
                ('person', models.ForeignKey(on_delete=models.CASCADE, blank=True, to='persons.Person', null=True)),
                ('user', models.ForeignKey(on_delete=models.CASCADE, blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonEmail',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_on', models.DateField(auto_now_add=True, null=True)),
                ('modified_on', models.DateField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.CharField(max_length=255, null=True, blank=True)),
                ('last_modified_by', models.CharField(max_length=255, null=True, blank=True)),
                ('share', models.CharField(blank=True, max_length=5, null=True, choices=[(b'', b''), (b'Y', b'Y'), (b'N', b'N')])),
                ('attachment', models.FileField(null=True, upload_to=persons.models.get_person_storage_path, blank=True)),
                ('email_address', models.CharField(max_length=255, null=True, blank=True)),
                ('instruction', models.CharField(max_length=255, null=True, blank=True)),
                ('email_type', models.ForeignKey(on_delete=models.CASCADE, blank=True, to='persons.EmailType', null=True)),
                ('person', models.ForeignKey(on_delete=models.CASCADE, blank=True, to='persons.Person', null=True)),
                ('user', models.ForeignKey(on_delete=models.CASCADE, blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonEmergencyContact',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_on', models.DateField(auto_now_add=True, null=True)),
                ('modified_on', models.DateField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.CharField(max_length=255, null=True, blank=True)),
                ('last_modified_by', models.CharField(max_length=255, null=True, blank=True)),
                ('share', models.CharField(blank=True, max_length=5, null=True, choices=[(b'', b''), (b'Y', b'Y'), (b'N', b'N')])),
                ('attachment', models.FileField(null=True, upload_to=persons.models.get_person_storage_path, blank=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=25, null=True, blank=True)),
                ('email_address', models.CharField(max_length=25, null=True, blank=True)),
                ('weblink', models.CharField(max_length=255, null=True, blank=True)),
                ('ordering', models.DecimalField(null=True, max_digits=10, decimal_places=1, blank=True)),
                ('title', models.CharField(max_length=255, null=True, blank=True)),
                ('relationship', models.CharField(max_length=255, null=True, blank=True)),
                ('person', models.ForeignKey(on_delete=models.CASCADE, blank=True, to='persons.Person', null=True)),
                ('user', models.ForeignKey(on_delete=models.CASCADE, blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'ordering': ['ordering', 'last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='PersonPhone',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_on', models.DateField(auto_now_add=True, null=True)),
                ('modified_on', models.DateField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.CharField(max_length=255, null=True, blank=True)),
                ('last_modified_by', models.CharField(max_length=255, null=True, blank=True)),
                ('share', models.CharField(blank=True, max_length=5, null=True, choices=[(b'', b''), (b'Y', b'Y'), (b'N', b'N')])),
                ('attachment', models.FileField(null=True, upload_to=persons.models.get_person_storage_path, blank=True)),
                ('phone_number', models.CharField(max_length=255, null=True, blank=True)),
                ('extension', models.CharField(max_length=255, null=True, blank=True)),
                ('instruction', models.CharField(max_length=255, null=True, blank=True)),
                ('person', models.ForeignKey(on_delete=models.CASCADE, blank=True, to='persons.Person', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonStatus',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_on', models.DateField(auto_now_add=True, null=True)),
                ('modified_on', models.DateField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.CharField(max_length=255, null=True, blank=True)),
                ('last_modified_by', models.CharField(max_length=255, null=True, blank=True)),
                ('share', models.CharField(blank=True, max_length=5, null=True, choices=[(b'', b''), (b'Y', b'Y'), (b'N', b'N')])),
                ('the_name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=models.CASCADE, blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneType',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_on', models.DateField(auto_now_add=True, null=True)),
                ('modified_on', models.DateField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.CharField(max_length=255, null=True, blank=True)),
                ('last_modified_by', models.CharField(max_length=255, null=True, blank=True)),
                ('share', models.CharField(blank=True, max_length=5, null=True, choices=[(b'', b''), (b'Y', b'Y'), (b'N', b'N')])),
                ('attachment', models.FileField(null=True, upload_to=persons.models.get_person_storage_path, blank=True)),
                ('the_name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=models.CASCADE, blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='personphone',
            name='phone_type',
            field=models.ForeignKey(on_delete=models.CASCADE, blank=True, to='persons.PhoneType', null=True),
        ),
        migrations.AddField(
            model_name='personphone',
            name='user',
            field=models.ForeignKey(on_delete=models.CASCADE, blank=True, to=settings.AUTH_USER_MODEL, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='person_status',
            field=models.ForeignKey(on_delete=models.CASCADE, blank=True, to='persons.PersonStatus', null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='user',
            field=models.ForeignKey(on_delete=models.CASCADE, blank=True, to=settings.AUTH_USER_MODEL, null=True),
        ),
    ]
