# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-06 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_auto_20160323_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='is_reviewer',
            field=models.CharField(blank=True, choices=[('', ''), ('Y', 'Yes'), ('N', 'No')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='personemergencycontact',
            name='share',
            field=models.CharField(blank=True, choices=[('', ''), ('Y', 'Yes'), ('N', 'No')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='personstatus',
            name='share',
            field=models.CharField(blank=True, choices=[('', ''), ('Y', 'Yes'), ('N', 'No')], max_length=5, null=True),
        ),
    ]
