# Generated by Django 3.0.3 on 2020-02-24 21:29

import constants.utils
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowsa', '0002_auto_20200224_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/uploads', location='F:\\Git\\projects\\epa\\datasearch\\DataSearch\\DataSearch\\uploads'), upload_to=constants.utils.get_flowsa_storage_path),
        ),
    ]
