# Generated by Django 3.0.3 on 2020-02-25 10:50

import constants.utils
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowsa', '0003_auto_20200224_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/uploads', location='.\\DataSearch\\uploads'), upload_to=constants.utils.get_flowsa_storage_path),
        ),
    ]
