# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-09 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0004_rmsprojectattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='IRMS_project_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.RemoveField(
            model_name='task',
            name='projects',
        ),
        migrations.AlterField(
            model_name='project',
            name='rms_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='RMSproject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rms.Project', to_field='rms_id'),
        ),
        migrations.AlterField(
            model_name='program',
            name='rms_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rms.Program', to_field='rms_id'),
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='rms.Project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rms.Program'),
        ),
        migrations.AlterField(
            model_name='task',
            name='RMSproject_id',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='task',
            name='program',
            field=models.ForeignKey(default=224, on_delete=django.db.models.deletion.CASCADE, to='rms.Program'),
            preserve_default=False,
        ),
    ]
