# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-10 20:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0006_program_show_project'),
        ('rms', '0005_auto_20180406_1916'),
    ]

    operations = [
    ]
