# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-10 20:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0007_merge_20180410_2038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='show_project',
            new_name='show_projects',
        ),
    ]
