# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-10 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0008_auto_20180410_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='title',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
