# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-13 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0010_auto_20180410_2047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['epa_id']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['epa_id']},
        ),
        migrations.AlterField(
            model_name='program',
            name='acronym',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='program',
            name='rms_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='program',
            name='url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
