# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-06 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks_tab', '0006_auto_20171211_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebookstab',
            name='participating_orgs',
            field=models.ManyToManyField(blank=True, to='projects.ParticipatingOrganization'),
        ),
        migrations.AlterField(
            model_name='notebookstab',
            name='programs',
            field=models.ManyToManyField(blank=True, to='projects.Program'),
        ),
        migrations.AlterField(
            model_name='notebookstab',
            name='projects',
            field=models.ManyToManyField(blank=True, to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='notebookstab',
            name='schedule_review',
            field=models.CharField(choices=[('', ''), ('Y', 'Yes'), ('N', 'No')], default='N', max_length=2),
        ),
        migrations.AlterField(
            model_name='notebookstab_notebookstatus',
            name='is_active',
            field=models.CharField(blank=True, choices=[('', ''), ('Y', 'Yes'), ('N', 'No')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='notebookstab_status',
            name='is_active',
            field=models.CharField(blank=True, choices=[('', ''), ('Y', 'Yes'), ('N', 'No')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='notebookstab_type',
            name='is_active',
            field=models.CharField(blank=True, choices=[('', ''), ('Y', 'Yes'), ('N', 'No')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='notebookstabattachment',
            name='include_in_email',
            field=models.CharField(choices=[('', ''), ('Y', 'Yes'), ('N', 'No')], default='N', max_length=2),
        ),
        migrations.AlterField(
            model_name='notebookstabattachment',
            name='is_review_file',
            field=models.CharField(choices=[('', ''), ('Y', 'Yes'), ('N', 'No')], default='N', max_length=2),
        ),
    ]
