# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-11 15:30
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notebooks_tab', '0008_notebookstab_notebookreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotebooksTab_Recent_Emails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_last_sent', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notebooks_tab_notebookstab_recent_emails',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NotebooksTab_Recent_Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reviewed', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notebooks_tab_notebookstab_recent_reviews',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NotebooksTab_User_Notebooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbtab_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('roles', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('review_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
            ],
            options={
                'db_table': 'notebooks_tab_notebookstab_user_notebooks',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='notebookstab_reviews',
            options={},
        ),
        migrations.AddField(
            model_name='notebookstab_reviews',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notebookstab_reviews',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notebookstab_schedule_review',
            name='nbtab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notebooks_tab.NotebooksTab'),
        ),
    ]
