# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-15 15:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import notebooks_tab.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notebooks_tab', '0009_auto_20180511_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotebooksTabReviewAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('last_modified_by', models.CharField(blank=True, max_length=255, null=True)),
                ('attachment', models.FileField(blank=True, max_length=255, null=True, upload_to=notebooks_tab.models.get_nbtab_attachment_storage_path)),
                ('the_name', models.CharField(blank=True, max_length=255, null=True)),
                ('the_size', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['the_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='notebookstab_reviews',
            options={'ordering': ['-date_reviewed']},
        ),
        migrations.AddField(
            model_name='notebookstabreviewattachment',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nb_review_attachments', to='notebooks_tab.NotebooksTab_Reviews'),
        ),
        migrations.AddField(
            model_name='notebookstabreviewattachment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
