# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-15 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import notebooks_tab.models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks_tab', '0010_auto_20180515_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebookstabreviewattachment',
            name='attachment',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=notebooks_tab.models.get_review_attachment_storage_path),
        ),
    ]
