# Generated by Django 2.0.5 on 2018-05-17 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks_tab', '0012_auto_20180516_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notebookstab',
            name='date_reviewed',
        ),
        migrations.RemoveField(
            model_name='notebookstab',
            name='nb_status',
        ),
    ]
