# Generated by Django 2.0.5 on 2018-05-17 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks_tab', '0013_auto_20180517_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notebookstab',
            name='schedule_review',
        ),
    ]
