# Generated by Django 2.2.6 on 2019-10-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodWaste', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExistingDataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
