# Generated by Django 2.2.6 on 2019-10-30 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodWaste', '0002_existingdatasource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='existingdata',
            name='article_title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='existing_data_sources', to='FoodWaste.ExistingDataSource'),
            preserve_default=False,
        ),
    ]
