# Generated by Django 2.2.6 on 2019-11-01 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodWaste', '0003_auto_20191030_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='existingdata',
            old_name='article_title',
            new_name='source_title',
        ),
    ]
