# Generated by Django 2.2.7 on 2019-12-18 17:22
# pylint: skip-file

import os
from django.core import serializers
from django.db import migrations, transaction
from django.db.utils import IntegrityError

fixture_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '../fixtures'))
fixture_filename = 'existingdatasource.json'

def load_fixture(_apps, _schema_editor):
    """Load data from a fixture when running migrations"""
    fixture_file = os.path.join(fixture_dir, fixture_filename)
    fixture = open(fixture_file, 'rb')
    objects = serializers.deserialize('json', fixture, ignorenonexistent=True)
    for obj in objects:
        try:
            with transaction.atomic():
                obj.save()
        except IntegrityError:
            pass    # Ignore if duplicate obj already exists in db
    fixture.close()

class Migration(migrations.Migration):

    dependencies = [
        ('FoodWaste', '0006_auto_20191101_1348'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
