# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-06 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0002_auto_20160323_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audittype',
            name='is_active',
            field=models.CharField(blank=True, choices=[('', ''), ('Y', 'Yes'), ('N', 'No')], max_length=4, null=True),
        ),
    ]
