# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-06 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userdropdowninfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestsubject',
            name='is_active',
            field=models.CharField(blank=True, choices=[('', ''), ('Y', 'Yes'), ('N', 'No')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='can_create_users',
            field=models.CharField(blank=True, choices=[('', ''), ('Y', 'Yes'), ('N', 'No')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='can_edit',
            field=models.CharField(blank=True, choices=[('', ''), ('Y', 'Yes'), ('N', 'No')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='display_in_dropdowns',
            field=models.CharField(choices=[('', ''), ('Y', 'Yes'), ('N', 'No')], db_index=True, default='Y', max_length=2),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_reviewer',
            field=models.CharField(blank=True, choices=[('', ''), ('Y', 'Yes'), ('N', 'No')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_technical_lead',
            field=models.CharField(blank=True, choices=[('', ''), ('Y', 'Yes'), ('N', 'No')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('SUPER', 'SUPER USER'), ('OFFICE', 'OFFICE'), ('ALL', 'ALL LABS'), ('LAB', 'SINGLE LAB'), ('DIVISION', 'DIVISION USER'), ('BRANCH', 'BRANCH USER')], max_length=45, null=True),
        ),
    ]
