# Generated by Django 2.0.5 on 2018-11-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20180604_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='permissions',
            field=models.CharField(choices=[('READER', 'READER'), ('EDITOR', 'EDITOR'), ('SUPER USER', 'SUPER USER')], default='READER', max_length=45),
        ),
    ]
