# Generated by Django 2.1.3 on 2018-12-13 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_userprofile_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='permissions',
            field=models.CharField(choices=[('READER', 'READER'), ('EDITOR', 'EDITOR'), ('ADMIN', 'ADMIN')], default='READER', max_length=45),
        ),
    ]
